DELETE FROM `task_plan_balancesheet_detail`;
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (101,100,1,0,'Windows-31J','test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (201,200,1,0,'Windows-31J','test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (301,300,1,1,'Windows-31J','test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (401,400,1,0,'Windows-31J','test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (501,500,1,0,'Windows-31J','test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (601,600,0,0,'Windows-31J','test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (701,700,1,0,null,'test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
INSERT INTO `task_plan_balancesheet_detail` (`task_plan_balancesheet_detail_id`,`task_plan_balancesheet_detail_code`,`saishin_kbn`,`is_finished`,`charset`,`child_dir`,`file_name`,`full_path`,`shoshou_id`,`Shoshou_code`,`Shoshou_kbn`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`update_user_id`,`update_user_code`,`update_user_name`,`update_timestamp`) VALUES (801,800,1,0,'Windows-31J','test_user/expand','2022_ホリエモン新党_SYUUSI.xml','test_user/expand/2022_ホリエモン新党_SYUUSI.xml',3,3,1,1,1,'ユーザ','2022-12-01 00:00:00',0,0,'','2024-11-08 06:27:21');
