CREATE TABLE `offering_party_usage_0804_report_2025` (
  `party_usage_0804_report_id` bigint NOT NULL AUTO_INCREMENT COMMENT '使途報告書様式8その4Id',
  `party_usage_0804_report_code` bigint DEFAULT NULL COMMENT '使途報告書様式8その4同一識別コード',
  `saishin_kbn` int DEFAULT NULL COMMENT '最新区分\n',
  `document_code` bigint DEFAULT NULL COMMENT '文書同一識別コード',
  `nendo` int DEFAULT NULL COMMENT '報告年度',
  `offering_date` date DEFAULT NULL COMMENT '提出日',
  `political_organization_id` bigint DEFAULT NULL COMMENT '政治団体Id',
  `political_organization_code` int DEFAULT NULL COMMENT '政治団体同一識別コード',
  `political_organization_name` varchar(210) DEFAULT NULL COMMENT '政治団体名称',
  `dantai_name` varchar(210) DEFAULT NULL COMMENT '原文書政治団体名称',
  `daihyou_name` varchar(210) DEFAULT NULL COMMENT '原文書政治団体代表者名',
  `relation_kbn` int DEFAULT NULL COMMENT '関連者区分',
  `relation_person_id_delegate` bigint DEFAULT NULL COMMENT '代表者関連者Id',
  `relation_person_code_delegate` int DEFAULT NULL COMMENT '代表者関連者同一識別コード',
  `relation_person_name_delegate` varchar(210) DEFAULT NULL COMMENT '代表者関連者名称',
  `shishutsu_kbn` int DEFAULT NULL COMMENT '区分',
  `shishutsu_kbn_name` varchar(210) DEFAULT NULL COMMENT '区分名称',
  `sheet_himoku` varchar(210) DEFAULT NULL COMMENT 'シート費目',
  `sheet_amount_all` bigint DEFAULT NULL COMMENT 'シート全合計',
  `sheet_amount_all_koufukin` bigint DEFAULT NULL COMMENT 'シート全合計交付金充当',
  `sheet_amount_all_my_funds` bigint DEFAULT NULL COMMENT 'シート全合計自党基金充当',
  `sheet_amount_sonota` bigint DEFAULT NULL COMMENT 'シート全合計',
  `sheet_amount_sonota_koufukin` varchar(20) DEFAULT NULL COMMENT 'シート全合計交付金充当',
  `sheet_amount_sonota_my_funds` varchar(20) DEFAULT NULL COMMENT 'シート全合計自党基金充当',
  `row_no` int DEFAULT NULL COMMENT '行番号',
  `usage_item` varchar(210) DEFAULT NULL COMMENT '使用項目',
  `amount_all` bigint DEFAULT NULL COMMENT '支出金額',
  `amount_koufukin` bigint DEFAULT NULL COMMENT '交付金充当支出金額',
  `amount_my_funds` bigint DEFAULT NULL COMMENT '交付金充当支出金額',
  `accrual_date` varchar(40) DEFAULT NULL COMMENT '発生日',
  `accrual_date_value` date DEFAULT NULL COMMENT '発生日実値',
  `payee_name` varchar(210) DEFAULT NULL COMMENT '支払者',
  `address` varchar(210) DEFAULT NULL COMMENT '支払者住所',
  `bikou` varchar(210) DEFAULT NULL COMMENT '備考',
  `flg_collect_recipt` int DEFAULT NULL COMMENT '領収所徴収フラグ',
  `relation_kbn_payee` int DEFAULT NULL COMMENT '支払者関連者区分',
  `relation_person_id_payee` bigint DEFAULT NULL COMMENT '支払者関連者Id(個人)',
  `relation_person_code_payee` int DEFAULT NULL COMMENT '支払者関連者同一識別コード(個人)',
  `relation_person_name_payee` varchar(210) DEFAULT NULL COMMENT '支払者関連者名称(個人)',
  `relation_corp_id_payee` bigint DEFAULT NULL COMMENT '支払者関連者Id(法人)',
  `relation_corp_code_payee` int DEFAULT NULL COMMENT '支払者関連者同一識別コード(法人)',
  `relation_corp_name_payee` varchar(210) DEFAULT NULL COMMENT '支払者関連者Id(法人)',
  `relation_political_org_id_payee` bigint DEFAULT NULL COMMENT '支払者関連者同一識別コード(政治団体)',
  `relation_political_org_code_payee` int DEFAULT NULL COMMENT '支払者関連者名称(政治団体)',
  `relation_political_org_name_payee` varchar(210) DEFAULT NULL COMMENT '支払者関連者名称(政治団体)',
  `insert_user_id` bigint DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザ同一識別コード',
  `insert_user_name` varchar(300) DEFAULT NULL COMMENT '挿入ユーザ姓名',
  `insert_timestamp` timestamp NULL DEFAULT NULL COMMENT '挿入タイムスタンプ',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新ユーザId',
  `update_user_code` int DEFAULT NULL COMMENT '更新ユーザ同一識別コード',
  `update_user_name` varchar(300) DEFAULT NULL COMMENT '更新ユーザ姓名',
  `update_timestamp` timestamp NULL DEFAULT NULL COMMENT '更新タイムスタンプ',
  PRIMARY KEY (`party_usage_0804_report_id`)
) ENGINE=InnoDB AUTO_INCREMENT=377 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
