CREATE TABLE `political_organization` (
  `political_organization_id` bigint NOT NULL AUTO_INCREMENT COMMENT '政治団体Id',
  `political_organization_code` int DEFAULT NULL COMMENT '政治団体同一識別コード',
  `political_organization_name` varchar(100) DEFAULT NULL COMMENT '政治団体名称',
  `saishin_kbn` smallint DEFAULT NULL COMMENT '最新区分',
  `political_organization_name_kana` varchar(150) DEFAULT NULL COMMENT '政治団体名称かな',
  `dantai_kbn` varchar(3) DEFAULT NULL COMMENT '政治団体区分',
  `address_all` text COMMENT '全住所',
  `daihyosha_user_id` bigint DEFAULT NULL COMMENT '代表者のユーザId',
  `daihyosha_user_code` int DEFAULT NULL COMMENT '代表者のユーザ同一識別コード',
  `daihyosha_name` varchar(200) DEFAULT NULL COMMENT '代表者の姓名',
  `daihyosha_first_name` varchar(50) DEFAULT NULL COMMENT '代表者の姓',
  `daihyosha_last_name` varchar(50) DEFAULT NULL COMMENT '代表者の名',
  `daihyosha_middle_name` varchar(50) DEFAULT NULL COMMENT '代表者ミドルネーム',
  `daihyosha_first_name_kana` varchar(150) DEFAULT NULL COMMENT '代表者姓かな',
  `daihyosha_last_name_kana` varchar(150) DEFAULT NULL COMMENT '代表者名かな',
  `kaikei_sekininsha_user_id` bigint DEFAULT NULL COMMENT '会計責任者のユーザId',
  `kaikei_sekininsha_user_code` int DEFAULT NULL COMMENT '会計責任者のユーザ同一識別コード',
  `kaikei_sekininsha_name` varchar(200) DEFAULT NULL COMMENT '会計責任者の姓名',
  `kaikei_sekininsha_first_name` varchar(50) DEFAULT NULL COMMENT '会計責任者の姓',
  `kaikei_sekininsha_last_name` varchar(50) DEFAULT NULL COMMENT '会計責任者の名',
  `kaikei_sekininsha_middle_name` varchar(50) DEFAULT NULL COMMENT '会計責任者ミドルネーム',
  `kaikei_sekininsha_first_name_kana` varchar(150) DEFAULT NULL COMMENT '会計責任者姓かな',
  `kaikei_sekininsha_last_name_kana` varchar(150) DEFAULT NULL COMMENT '会計責任者名かな',
  `kaikei_daiko_user_id` bigint DEFAULT NULL COMMENT '会計責任者の代行者ユーザId',
  `kaikei_daiko_user_code` int DEFAULT NULL COMMENT '会計責任者の代行者ユーザ同一識別コード',
  `kaikei_daiko_name` varchar(200) DEFAULT NULL COMMENT '会計責任者の代行者姓名',
  `kaikei_daiko_first_name` varchar(50) DEFAULT NULL COMMENT '会計責任者代行者の姓',
  `kaikei_daiko_last_name` varchar(50) DEFAULT NULL COMMENT '会計責任者代行者の名',
  `kaikei_daiko_middle_name` varchar(50) DEFAULT NULL COMMENT '会計責任者代行者ミドルネーム',
  `kaikei_daiko_first_name_kana` varchar(150) DEFAULT NULL COMMENT '会計責任者代行者姓かな',
  `kaikei_daiko_last_name_kana` varchar(150) DEFAULT NULL COMMENT '会計責任者代行者名かな',
  `search_text` text COMMENT '自由検索用カラム',
  `insert_user_id` bigint DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザ同一識別コード',
  `insert_user_name` varchar(300) DEFAULT NULL COMMENT '挿入ユーザ姓名',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入タイムスタンプ',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新ユーザId',
  `update_user_code` int DEFAULT NULL COMMENT '更新ユーザ同一識別コード',
  `update_user_name` varchar(300) DEFAULT NULL COMMENT '更新ユーザ姓名',
  `update_timestamp` datetime DEFAULT NULL COMMENT '更新タイムスタンプ',
  PRIMARY KEY (`political_organization_id`),
  FULLTEXT KEY `search_words` (`search_text`) /*!50100 WITH PARSER `ngram` */ 
) ENGINE=InnoDB AUTO_INCREMENT=800 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci