CREATE TABLE `political_balancesheet_shuushi07_01` (
  `political_organization_id` bigint NOT NULL COMMENT '政治団体Id',
  `political_organization_code` int NOT NULL COMMENT '政治団体同一識別コード',
  `political_organization_name` varchar(100) DEFAULT NULL COMMENT '政治団体名称',
  `latest_kbn` tinyint DEFAULT NULL COMMENT '最新区分',
  `houkoku_nen` int NOT NULL COMMENT '提出年',
  `kaisai_date` date DEFAULT NULL COMMENT '特定パーティ開催年月日',
  `dantai_nm` varchar(100) DEFAULT NULL COMMENT '政治団体名称',
  `dantai_kana` varchar(200) DEFAULT NULL COMMENT '政治団体名称かな',
  `jim_adr` varchar(600) DEFAULT NULL,
  `jim_apa_adr` varchar(100) DEFAULT NULL,
  `dai_nm1` varchar(50) DEFAULT NULL,
  `dai_nm2` varchar(50) DEFAULT NULL,
  `kai_nm1` varchar(45) DEFAULT NULL,
  `kai_nm2` varchar(45) DEFAULT NULL,
  `tantou1_nm1` varchar(45) DEFAULT NULL,
  `tantou1_nm2` varchar(45) DEFAULT NULL,
  `tantou1_tel` varchar(45) DEFAULT NULL,
  `tantou2_nm1` varchar(45) DEFAULT NULL,
  `tantou2_nm2` varchar(45) DEFAULT NULL,
  `tantou2_tel` varchar(45) DEFAULT NULL,
  `tantou3_nm1` varchar(45) DEFAULT NULL,
  `tantou3_nm2` varchar(45) DEFAULT NULL,
  `tantou3_tel` varchar(45) DEFAULT NULL,
  `dantai_kbn` tinyint DEFAULT NULL,
  `katsudou_kuiki` tinyint DEFAULT NULL,
  `sikin_umu` tinyint DEFAULT NULL,
  `koushoku_nm` varchar(100) DEFAULT NULL,
  `koushoku_kbn` tinyint DEFAULT NULL,
  `shikin_todoke_nm1` varchar(45) DEFAULT NULL,
  `shikin_todoke_nm2` varchar(45) DEFAULT NULL,
  `shikin_kikan1` date DEFAULT NULL,
  `shikin_kikan2` date DEFAULT NULL,
  `shikin_kikan_fukusu` varchar(150) DEFAULT NULL,
  `giin_dantai_kbn` tinyint DEFAULT NULL,
  `giin1_koshoku_nm1` varchar(50) DEFAULT NULL,
  `giin1_koshoku_nm2` varchar(50) DEFAULT NULL,
  `giin1_koshoku_nm` varchar(200) DEFAULT NULL,
  `giin1_koshoku_kbn` tinyint DEFAULT NULL,
  `giin1_kikan1` date DEFAULT NULL,
  `giin1_kik1n2` date DEFAULT NULL,
  `giin_kikan_fukusu` varchar(200) DEFAULT NULL,
  `giin2_koshoku_nm1` varchar(50) DEFAULT NULL,
  `giin3_koshoku_nm1` varchar(50) DEFAULT NULL,
  `giin2_koshoku_nm2` varchar(50) DEFAULT NULL,
  `giin3_koshoku_nm2` varchar(50) DEFAULT NULL,
  `giin2_koshoku_nm` varchar(50) DEFAULT NULL,
  `giin3_koshoku_nm` varchar(50) DEFAULT NULL,
  `giin2_koshoku_kbn` tinyint DEFAULT NULL,
  `giin3_koshoku_kbn` tinyint DEFAULT NULL,
  `insert_user_id` bigint DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザ同一識別コード',
  `insert_user_name` varchar(300) DEFAULT NULL COMMENT '挿入ユーザ姓名',
  `insert_timestamp` timestamp NULL DEFAULT NULL COMMENT '挿入タイムスタンプ',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新ユーザId',
  `update_user_code` int DEFAULT NULL COMMENT '更新ユーザ同一識別コード',
  `update_user_name` varchar(300) DEFAULT NULL COMMENT '更新ユーザ姓名',
  `update_timestamp` timestamp NULL DEFAULT NULL COMMENT '更新タイムスタンプ',
  PRIMARY KEY (`political_organization_id`,`political_organization_code`,`houkoku_nen`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci