CREATE TABLE `user_web_access` (
  `user_web_access_id` bigint NOT NULL COMMENT 'ユーザWeb連絡先Id',
  `user_web_access_code` int DEFAULT NULL COMMENT 'ユーザWeb連絡先同一識別コード',
  `saishin_kbn` tinyint DEFAULT NULL COMMENT '最新区分',
  `user_id` bigint DEFAULT NULL COMMENT '登録ユーザId',
  `user_code` int DEFAULT NULL COMMENT '登録ユーザ同一識別コード',
  `user_name` varchar(300) DEFAULT NULL COMMENT '登録ユーザ姓名',
  `kengen_kbn` int DEFAULT NULL COMMENT '権限区分',
  `mail_address` varchar(300) DEFAULT NULL COMMENT 'メールアドレス',
  `sns_id` bigint DEFAULT NULL COMMENT 'SNSId',
  `sns_code` int DEFAULT NULL COMMENT 'SNS同一識別コード',
  `sns_name` varchar(300) DEFAULT NULL COMMENT 'SNS名称',
  `send_sns_logic_id` int DEFAULT NULL COMMENT '送信LogicId',
  `insert_user_id` bigint DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザ同一識別コード',
  `insert_user_name` varchar(300) DEFAULT NULL COMMENT '挿入ユーザ姓名',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入タイムスタンプ',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新ユーザId',
  `update_user_code` int DEFAULT NULL COMMENT '更新ユーザ同一識別コード',
  `update_user_name` varchar(300) DEFAULT NULL COMMENT '更新ユーザ姓名',
  `update_timestamp` datetime DEFAULT NULL COMMENT '更新タイムスタンプ',
  PRIMARY KEY (`user_web_access_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
